### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by YannickFricke** [yonascode/Candy#2]
1. CandyAction.enum.php //no "enum" in file names
2. public function newBuilder($action) { return new CandyBuilder($this, $action); }  // check the action
3. Use PHPUnit for tests
4. no standard values
5. Create documentation with doxygen
6. Integrate TravisCI
7. Add a project description to the readme
8. Write variables on several lines instead in one line
9. Use an interface for comming integrations
10. Documentate all functions and variables

**Comment by jan-krueger** [comment]
Thank you for your feedback. The most important points are done and the rest is done when it's done.
